// <auto-generated />
using System;
using KRT.Onboarding.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KRT.Onboarding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    partial class OnboardingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KRT.Onboarding.Domain.Contas.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em_utc");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_titular");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("KRT.Onboarding.Domain.Contas.Conta", b =>
                {
                    b.OwnsOne("KRT.Onboarding.Domain.Contas.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ContaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character(11)")
                                .HasColumnName("cpf")
                                .IsFixedLength();

                            b1.HasKey("ContaId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ux_contas_cpf");

                            b1.ToTable("contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
